## 数据操作
### tensor操作

### 1.tensor的创建

In [2]:
import torch
x=torch.empty(5,3)#5*3的未初始化的tensor
print(x)

tensor([[9.1837e-39, 8.4490e-39, 1.0102e-38],
        [1.0561e-38, 1.0286e-38, 1.0653e-38],
        [1.0469e-38, 9.5510e-39, 9.9184e-39],
        [9.0000e-39, 1.0561e-38, 1.0653e-38],
        [4.1327e-39, 8.9082e-39, 9.8265e-39]])


In [2]:
x=torch.rand(5,3)#随机初始化的tensor
print(x)

tensor([[0.0889, 0.5923, 0.2946],
        [0.4116, 0.3431, 0.3291],
        [0.2632, 0.8994, 0.8653],
        [0.6747, 0.2467, 0.4824],
        [0.8485, 0.5676, 0.8477]])


In [3]:
x=torch.zeros(5,3,dtype=torch.long)#long型全0的tensor
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [4]:
x=torch.tensor([5.5,3])#直接用数据创建
print(x)

tensor([5.5000, 3.0000])


In [7]:
x=x.new_ones(5,3,dtype=torch.float64) #使用已有的tensor来创建，默认重用一些属性
print(x)

x=torch.randn_like(x,dtype=torch.float)#制定新的数据类型
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-5.1612e-01, -1.0816e-01,  1.4252e-03],
        [-1.1978e-01,  1.1110e+00, -2.7205e-01],
        [-4.6467e-02, -3.3716e-01, -1.6166e+00],
        [-2.9310e-01,  1.2526e+00, -1.6284e+00],
        [-6.2475e-01, -2.0883e+00,  5.1083e-01]])


In [8]:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


### 2.tensor的操作

#### 加法

In [10]:
y=torch.rand(5,3)
print(x+y)  #加法形式一

tensor([[ 0.2426,  0.5949,  0.0682],
        [ 0.1195,  1.1386,  0.7269],
        [ 0.1535, -0.1836, -0.6945],
        [-0.0986,  2.2287, -1.4086],
        [-0.1263, -1.7757,  0.6453]])


In [12]:
print(torch.add(x,y))#:加法形式二

tensor([[ 0.2426,  0.5949,  0.0682],
        [ 0.1195,  1.1386,  0.7269],
        [ 0.1535, -0.1836, -0.6945],
        [-0.0986,  2.2287, -1.4086],
        [-0.1263, -1.7757,  0.6453]])


In [13]:
result=torch.empty(5,3)
torch.add(x,y,out=result) #指定输出
print(result)

tensor([[ 0.2426,  0.5949,  0.0682],
        [ 0.1195,  1.1386,  0.7269],
        [ 0.1535, -0.1836, -0.6945],
        [-0.0986,  2.2287, -1.4086],
        [-0.1263, -1.7757,  0.6453]])


In [14]:
# adds x to y
y.add_(x) #加法形式三 inplace pytorch中inplace版本都有后缀_,如x.copy_(y)
print(y)

tensor([[ 0.2426,  0.5949,  0.0682],
        [ 0.1195,  1.1386,  0.7269],
        [ 0.1535, -0.1836, -0.6945],
        [-0.0986,  2.2287, -1.4086],
        [-0.1263, -1.7757,  0.6453]])


#### 索引
索引的结果与原数据共享内存，修改一个，另一个也会跟着修改

In [16]:
y=x[0,:]
y += 1
print(y)
print(x[0,:]) #改变y,原有的x也会改变

tensor([1.4839, 1.8918, 2.0014])
tensor([1.4839, 1.8918, 2.0014])


#### 改变形状
view()

In [17]:
y=x.view(15)
z=x.view(-1,5) #-1所指的维度可以根据其他维度推算出来
print(x.size(),y.size(),z.size())

torch.Size([5, 3]) torch.Size([15]) torch.Size([3, 5])


#### view()返回的新Tensor与源Tensor虽然可能有不同的size，但是是共享data的，也即更改其中的一个，另外一个也会跟着改变。(顾名思义，view仅仅是改变了对这个张量的观察角度-视图，内部数据并未改变)

In [18]:
x += 1
print(x)
print(y)#y也会+1

tensor([[ 2.4839,  2.8918,  3.0014],
        [ 0.8802,  2.1110,  0.7280],
        [ 0.9535,  0.6628, -0.6166],
        [ 0.7069,  2.2526, -0.6284],
        [ 0.3753, -1.0883,  1.5108]])
tensor([ 2.4839,  2.8918,  3.0014,  0.8802,  2.1110,  0.7280,  0.9535,  0.6628,
        -0.6166,  0.7069,  2.2526, -0.6284,  0.3753, -1.0883,  1.5108])


使用clone()函数返回真正的副本

In [21]:
x_cp=x.clone().view(15)
x -= 1
print(x)
print(x_cp)

tensor([[ 1.4839,  1.8918,  2.0014],
        [-0.1198,  1.1110, -0.2720],
        [-0.0465, -0.3372, -1.6166],
        [-0.2931,  1.2526, -1.6284],
        [-0.6247, -2.0883,  0.5108]])
tensor([ 2.4839,  2.8918,  3.0014,  0.8802,  2.1110,  0.7280,  0.9535,  0.6628,
        -0.6166,  0.7069,  2.2526, -0.6284,  0.3753, -1.0883,  1.5108])


使用clone还有一个好处是会被记录在计算图中，即梯度回传到副本时也会传到源Tensor。

另外一个常用的常用的函数就是item(), 它可以将一个标量Tensor转换成一个Python number：

In [22]:
x=torch.randn(1)
print(x)
print(x.item())

tensor([-1.2615])
-1.2615078687667847


#### 线性代数
另外，PyTorch还支持一些线性函数，具体用法参考官方文档。


### 3.广播机制
之前内容是如何对两个形状相同的Tensor做按元素运算。当对两个形状不同的Tensor按元素运算时，可能会触发广播（broadcasting）机制：先适当复制元素使这两个Tensor形状相同后再按元素运算。

In [3]:
x=torch.arange(1,3).view(1,2)
print(x)
y=torch.arange(1,4).view(3,1)
print(y)
print(x+y)

tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


由于x和y分别是1行2列和3行1列的矩阵，如果要计算x + y，那么x中第一行的2个元素被广播（复制）到了第二行和第三行，而y中第一列的3个元素被广播（复制）到了第二列。如此，就可以对2个3行2列的矩阵按元素相加。

### 4.运算的内存开销
索引操作是不会开辟新内存的，而像y = x + y这样的运算是会新开内存的，然后将y指向新内存。为了演示这一点，我们可以使用Python自带的id函数：如果两个实例的ID一致，那么它们所对应的内存地址相同；反之则不同。

In [4]:
x=torch.tensor([1,2])
y=torch.tensor([3,4])
id_before=id(y)
y=y+x
print(id(y)==id_before)

False


如果想指定结果到原来的y的内存，可以使用前面介绍的索引来进行替换操作。在下面的例子中，我们把x + y的结果通过[:]写进y对应的内存中。

In [5]:
x=torch.tensor([1,2])
y=torch.tensor([3,4])
id_before=id(y)
y[:]=x+y
print(id(y)==id_before)

True


我们还可以使用运算符全名函数中的out参数或者自加运算符+=(也即add_())达到上述效果，例如torch.add(x, y, out=y)和y += x(y.add_(x))。

In [6]:
x=torch.tensor([1,2])
y=torch.tensor([3,4])
id_before=id(y)
torch.add(x,y,out=y) #y+=x, y.add_(x)
print(id(y)==id_before)

True


### 5.Tensor和NumPy相互转换
用numpy()和from_numpy()将Tensor和NumPy中的数组相互转换。但是需要注意的一点是： 这两个函数所产生的的Tensor和NumPy中的数组共享相同的内存（所以他们之间的转换很快），改变其中一个时另一个也会改变！！！

还有一个常用的将NumPy中的array转换成Tensor的方法就是torch.tensor(), 需要注意的是，此方法总是会进行数据拷贝（就会消耗更多的时间和空间），所以返回的Tensor和原来的数据不再共享内存。

In [8]:
a=torch.ones(5)
b=a.numpy() #numpy()将tensor转为numpy数组
print(a,b)
a+=1 #共享内存
print(a,b)
b+=1
print(a,b)

tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]
tensor([3., 3., 3., 3., 3.]) [3. 3. 3. 3. 3.]


In [9]:
import numpy as np
a=np.ones(5)
b=torch.from_numpy(a)#from_numpy()将numpy数组转为tensor
print(a,b)

a+=1#共享内存
print(a,b)
b+=1
print(a,b)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[3. 3. 3. 3. 3.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


In [10]:
c=torch.tensor(a)#直接使用torch.tensor()，会进行拷贝，a和c不再共享内存

a += 1
print(a,c) 

[4. 4. 4. 4. 4.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


### 6.Tensor on GPU
用方法to()可以将Tensor在CPU和GPU（需要硬件支持）之间相互移动。

In [11]:
x=torch.ones(5)
# 以下代码只有在PyTorch GPU版本上才会执行
if torch.cuda.is_available():
    device=torch.device("cuda") #GPU
    y=torch.ones_like(x,device=device) #直接创建一个GPU上的tensor
    x=x.to(device) #等价于 x.to("cuda")
    z=x+y
    print(z)
    print(z.to("cpu",torch.double))#移动的同时也可以更改数据类型

tensor([2., 2., 2., 2., 2.], device='cuda:0')
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
